version: '3.8'

services:
  nginx:
    image: nginx:1.21-alpine
    container_name: modx_nginx
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites:/etc/nginx/conf.d
    depends_on:
      - php
    networks:
      - modx_network

  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: modx_php
    volumes:
      - ./www:/var/www
      - ./php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    environment:
      - PHP_MEMORY_LIMIT=256M
    networks:
      - modx_network

  mysql:
    image: mysql:5.7
    container_name: modx_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: modx_db
      MYSQL_USER: modx_user
      MYSQL_PASSWORD: modx_password
    command: [
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci',
      '--skip-character-set-client-handshake'
    ]
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - modx_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: modx_phpmyadmin
    environment:
      PMA_HOST: mysql  # Используем имя сервиса, а не localhost
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - modx_network

networks:
  modx_network:
    driver: bridge

volumes:
  mysql_data: